### ISSUE TITLE
Exception when disabling NApp

### ISSUE THREAD

**Issue by cemsbr** [kytos/of_stats#19]
```Exception in thread Thread-516:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/kytos/kytos/core/helpers.py", line 71, in threaded_handler
    handler(*args)
  File "/root/kytos-demo/var/lib/kytos/napps/kytos/of_stats/main.py", line 49, in listener
  File "/root/kytos-demo/var/lib/kytos/napps/../napps/kytos/of_stats/stats.py", line 353, in listen
  File "/root/kytos-demo/var/lib/kytos/napps/../napps/kytos/of_stats/stats.py", line 83, in update
rrdtool.OperationalError: opening '/root/kytos-demo/var/lib/kytos/napps/../napps/kytos/of_stats/rrd/flows/67:8c:08:9e:01:62:d6:36/d24f945c000d2e8195df2e6ebfdf54de.rrd': No such file or directory```

**Comment by cemsbr** [comment]
@macartur , could you check whether this error is still happening after disabling kytos/of_stats, please?
